openapi.download:
  path: '/openapi/{openapi_generator}'
  defaults:
    _title: 'OpenAPI Schema Download'
    _title_callback: 'Drupal\openapi\Controller\ApiSpecificationController::title'
    _controller: '\Drupal\openapi\Controller\ApiSpecificationController::getSpecification'
  methods:
    - GET
  requirements:
    _permission: 'access openapi api docs'
    _format: 'json'
  options:
    parameters:
      openapi_generator:
        type: openapi_generator
openapi.downloads:
  path: '/admin/config/services/openapi-downloads'
  defaults:
    _controller: '\Drupal\openapi\Controller\OpenApiDownloadController::downloadsList'
    _title: 'OpenAPI Downloads'
  methods:
    - GET
  requirements:
    _permission: 'access openapi api docs'
