name: OpenAPI Redoc Documentation
type: module
description: Documentation using the ReDoc
# core: 8.x
package: OpenAPI
dependencies:
  - openapi:openapi

# Information added by Drupal.org packaging script on 2018-06-10
version: '8.x-1.0-beta1'
core: '8.x'
project: 'openapi'
datestamp: 1528645984
